# Generated by Django 4.0.6 on 2023-07-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=70)),
                ('stemail', models.CharField(max_length=70)),
                ('stdep', models.CharField(max_length=50)),
            ],
        ),
    ]
